### ISSUE TITLE
`mgmanysearch` errors out with no arguments

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash_plugin_containment_search#17]
```
% sourmash scripts mgmanysearch

== This is sourmash version 4.8.7. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

Traceback (most recent call last):
  File "/home/ctbrown/.conda/envs/sarco/bin/sourmash", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ctbrown/.conda/envs/sarco/lib/python3.12/site-packages/sourmash/__main__.py", line 20, in main
    retval = mainmethod(args)
             ^^^^^^^^^^^^^^^^
  File "/home/ctbrown/.conda/envs/sarco/lib/python3.12/site-packages/sourmash_plugin_containment_search.py", line 116, in main
    return mg_many_search(args.queries, args.against,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ctbrown/.conda/envs/sarco/lib/python3.12/site-packages/sourmash_plugin_containment_search.py", line 271, in mg_many_search
    for query_filename in query_filenames:
TypeError: 'NoneType' object is not iterable
```

**Comment by ctb** [comment]
Fixed in #20, released in v0.4.5.
