### ISSUE TITLE
list index out of range error

### ISSUE THREAD

**Issue by AnneliektH** [sourmash-bio/sourmash_plugin_containment_search#6]
Files involved are in /group/ctbrowngrp2/scratch/annie/2024-binning-kmer/sourmash_sig/

Trying to run as follows:
sourmash scripts mgsearch ERR3211994.abund.k15.contigs.single.sig.gz ERR3211994.abund.k15.reads.sig.gz -o ERR3211994.abund.csv

Where contigs.single.sig.gz is signature file of the genomes, and k15.reads.sig.gz is signature of the metagenome reads. 
Getting the following error:

Traceback (most recent call last):
  File "/home/amhorst/mambaforge/envs/branchwater/bin/sourmash", line 11, in <module>
    sys.exit(main())
  File "/home/amhorst/mambaforge/envs/branchwater/lib/python3.10/site-packages/sourmash/__main__.py", line 19, in main
    retval = mainmethod(args)
  File "/home/amhorst/mambaforge/envs/branchwater/lib/python3.10/site-packages/sourmash_plugin_containment_search.py", line 68, in main
    return mgsearch(args.query_genome, args.metagenomes,
  File "/home/amhorst/mambaforge/envs/branchwater/lib/python3.10/site-packages/sourmash_plugin_containment_search.py", line 86, in mgsearch
    query_ss = query_ss[0]
IndexError: list index out of range

**Comment by ctb** [comment]
thanks!

specify `-k 15` for now.
